version: "3"

services:
  db:
    image: postgres
    hostname: db
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: s3cr3tp4ssw0rd
    ports:
      - 5432:5432
    restart: always
  app:
    image: interview_app:latest
    volumes:
      - ./src/:/go/src/
      - ./data/output/summary.txt:/data/output/summary.txt
    working_dir: /go/src/filestat
    env_file:
      - ./postgres/app.env
    depends_on:
      - db
    links:
      - db
    command: ["go", "run", "../app/main.go"]
    #command: go run ./app/main.go
