FROM golang:latest

WORKDIR /code
VOLUME ./src:/code
RUN go build ./filestat
#ENV GOPATH=/golib/
#RUN /usr/local/go/bin/go get github.com/julienschmidt/httprouter
#CMD /usr/local/go/bin/go run /code/app/main.go

#EXPOSE 10004
